alias c="clear"
alias l="ls -ath"
alias gc="git checkout"
alias gb="git branch"
alias gst="git status"
alias stst="stg status"
alias str="stg refresh"
alias stpu="stg push"
alias stpo="stg pop"
alias sts="stg series"
alias stsh="stg show"
alias cdl="cd ~/Documents/linux/"
alias cdi="cd ~/Documents/tools"
alias du="ncdu --color dark -rr -x --exclude .git --exclude node_modules"
alias gl="git log --oneline"
alias scpp="sshpass -p abc123 scp"
alias mygit="cd Documents/git/namespace/parthsl/"

